name: build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
          cache: true

      - name: Check dependencies
        run: |
          set -x
          cp go.mod go.mod.bak
          cp go.sum go.sum.bak
          go mod tidy
          diff go.mod.bak go.mod && echo "OK" || (echo "Please run 'go mod tidy' to clean up modules"; exit 1)
          diff go.sum.bak go.sum && echo "OK" || (echo "Please run 'go mod tidy' to clean up modules"; exit 1)
          set +x
