name: lint

on:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'latest'
          args: --timeout 3m0s
